project:
  type: website

website:
  title: ""
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "1a: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "1b: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "2a: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "2b: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
        - text: "3: Spatio-Temporal Point Patterns Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "4:  Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "5a:  Global Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
        - text: "5b:  Local Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
        - text: "6:  Geographical Segmentation with Spatially Constrained Clustering Techniques"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "7:  Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "8:  Geographically Weighted Predictive Models"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "9:  Modelling Geographic of Accessibility"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "10a:  Processing and Visualising Flow Data"
          href: "Hands-on_Ex/Hands-on_Ex10a/Hands-on_Ex10a.html"
        - text: "10b:  Calibrating Spatial Interaction Models with R"
          href: "Hands-on_Ex/Hands-on_Ex10b/Hands-on_Ex10b.html"
    - text: "Take-home Exercises"
      menu: 
        - text: "Take-home Exercise2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"             
    - text: "In-Class Exercises"
      menu: 
        - text: "In-class Exercise 3a : Interactive K-function"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03a.html"  
        - text: "In-class Exercise 3b : Preparing data for Public Good "
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03b.html"      
        - text: "In-class Exercise 4 : Spatial Weights and Applications "
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"  
        - text: "In-class Exercise 5 : Global and Local Measures of Spatial Autocorrelation "
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Exercise 6 : Preparation of LTA Data Mall Data "
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        - text: "In-class Exercise 7 : Geographically weighted regression (GWR) "
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
        - text: "In-class Exercise 8 : Geographically Weighted Predictive Models "
          href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
        - text: "In-class Exercise 9 : Modelling Geographic of Accessibility "
          href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: right
    css: styles.css




