project:
  type: website

website:
  title: ""
  navbar:
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "1a: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
        - text: "1b: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "2a: Geospatial Data Wrangling with R"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
        - text: "2b: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"
    - text: "Take-home Exercises"
      menu: 
        - text: "Take-home Exercise1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html" 
            
    - text: "In-Class Exercises"
      menu: 
        - text: "In-class Exercise1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    toc-location: right
    css: styles.css





