---
title: "In class Exercise 4:  Spatial Weights and Applications"
date: "15-Sep-25"
date-modified: "last-modified"
toc: true
toc-depth: 4
format: html
editor: visual
---

### The code 
:::{style='font-size: 1.50em"}

```{r}
pacman::p_load(sf, geostatsplot, tmap, tidyverse,knitr,GWmodel)
```

:::

```{r}
hunan_sf <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
#| echo: false

glimpse(hunan_sf)
```

```{r}
#| echo: false
# Setting theme

hunan_sf %>% 
  kable() %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                            fixed_thead = T)
```

## Import Aspatial csv File

Next, we will import *Hunan_2012.csv* into R by using `read_csv()` of **readr** package. The output is R dataframe class.

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
#| echo: false
glimpse(hunan2012)
```

```{r}
#| echo: false

hunan2012 %>% 
  kable() %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                            fixed_thead = T)
```

## Perform relational join

The code chunk below will be used to update the attribute table of *hunan*'s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe. This is performed by using `left_join()` of **dplyr** package.

```{r}
colnames(hunan_sf)
```

```{r}
colnames(hunan2012)
```

```{r}
hunan_sf <- left_join(hunan_sf,hunan2012)%>%
  select(1:3,7, 15,16,31,32)
```


